// Generated by Wrangler by running `wrangler types`

interface Env {
	MATCH_AUTH_MAPPINGS: KVNamespace;
	S3_ACCESS_KEY: string;
	S3_SECRET_KEY: string;
	S3_ENDPOINT: string;
	BUCKET_NAME: string;
	LINKSHARE_PREFIX: string;
}
